/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class serkenny_jnitools_NativeMethods */

#ifndef _Included_serkenny_jnitools_NativeMethods
#define _Included_serkenny_jnitools_NativeMethods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     serkenny_jnitools_NativeMethods
 * Method:    testHelloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_serkenny_jnitools_NativeMethods_testHelloWorld
  (JNIEnv *, jobject);

/*
 * Class:     serkenny_jnitools_NativeMethods
 * Method:    testClassNotFound
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_serkenny_jnitools_NativeMethods_testClassNotFound
  (JNIEnv *, jobject);

/*
 * Class:     serkenny_jnitools_NativeMethods
 * Method:    testConstructorNotFound
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_serkenny_jnitools_NativeMethods_testConstructorNotFound
  (JNIEnv *, jobject);

/*
 * Class:     serkenny_jnitools_NativeMethods
 * Method:    testAccessIntArray
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_serkenny_jnitools_NativeMethods_testAccessIntArray
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     serkenny_jnitools_NativeMethods
 * Method:    testAccessDoubleArray
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_serkenny_jnitools_NativeMethods_testAccessDoubleArray
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     serkenny_jnitools_NativeMethods
 * Method:    testAccessCharArray
 * Signature: ([C)V
 */
JNIEXPORT void JNICALL Java_serkenny_jnitools_NativeMethods_testAccessCharArray
  (JNIEnv *, jobject, jcharArray);

/*
 * Class:     serkenny_jnitools_NativeMethods
 * Method:    testCreateIntArray
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_serkenny_jnitools_NativeMethods_testCreateIntArray
  (JNIEnv *, jobject);

/*
 * Class:     serkenny_jnitools_NativeMethods
 * Method:    testCreateDoubleArray
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_serkenny_jnitools_NativeMethods_testCreateDoubleArray
  (JNIEnv *, jobject);

/*
 * Class:     serkenny_jnitools_NativeMethods
 * Method:    testCreateCharArray
 * Signature: ()[C
 */
JNIEXPORT jcharArray JNICALL Java_serkenny_jnitools_NativeMethods_testCreateCharArray
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
